const suppliers = [
  "A.D. MAIA INDUS","ABPEREIRA-ATUAL","AMERICANFLEX IN","ARAMOVEIS INDUS","ARAPLAC INDUSTR","ARTELY","ASCENSUS TRADIN","BECHARA","BOX TECNOLOGIA","CAEMMUN INDUSTR","CIPLAFE COMERCI","COMERCIO, INDUS","CONQUISTA INDUS","DDS INDUSTRIA E","DEMOBILE - INDU","DJ INDUSTRIA E","D'JUAN COLCHOES","DOBUE MOVELARIA","EDN MOVEIS INDU","ESTOF. HELLEN","ESTOFADOS LADD","FALCON","FIBRASCA QUIMIC","FLEXFORMA ESTOF","GAZIN INDUSTRIA","GNX INDUSTRIA E","GRALHA AZUL","GRUPO K1 S A","IND E COM DE CO","INDUSTRIA BRASI","INDUSTRIA DE MO","INDUSTRIA E COM","INOVE ANJOS","INTERNACIONAL F","ITATIAIA ELETRO","LINOFORTE MOVEI","LUCIANE INDUSTR","LUIZZI INDUSTRI","M. E. GONCALVES","MADEMARQUES MOV","MASTER COMFORT","MATRIX - INDUST","MOVEIS JAMES","MOVEIS LANZA EI","MOVEIS SAO CARL","NORDESTE FLEX I","OLIVAR MOVEIS L","OLIVINA","OTELLO","ORYON INDUSTRIA","PLUMATEX COLCHO","POLIMAN INDUSTR","POLITORNO MOVEI","PROVINCIA","RECONFLEX INDUS","ROMPINELI","SANTOS ANDIRA I","SIMBAL SP INDUS","SMP - INDUSTRIA","SOLAR MOVEIS LT","SOMOPAR-SOCIEDA","SONETTO MOVEIS","SONY BRASIL LTD","TELASUL INDUSTR","TRAMONTINA DELT","TUCANOS DISTRIB","UMAFLEX","UMAFLEX INDUSTR","V. E. F. DE BRI","VALDEMOVEIS IND","VIERO MOVEIS IN","V-JOY INDUSTRIA","W L DA SILVA PE","ZISSOU"
];
const exclusiveTerms = ["ASCENSUS","AC COMERCIAL","AC COMERCI","NELL","OTELLO","BRINOX"];
const issueMap = {
  colchao:[['afundamento','Afundamento','Produto cedeu ou deformou'],['barulho','Barulho ao usar','Ruídos, estalos ou rangidos'],['mola','Mola fazendo barulho','Ruído identificado nas molas'],['quebrada','Chegou quebrado','Dano percebido no recebimento'],['outro','Outro relato','Situação não listada']],
  estofado:[['afundamento','Afundamento','Assento ou encosto cedeu'],['barulho','Barulho ao usar','Ruídos, estalos ou rangidos'],['mola','Mola fazendo barulho','Ruído identificado nas molas'],['peca','Faltou ou quebrou uma peça','Componente isolado'],['outro','Outro relato','Situação não listada']],
  madeira:[['montagem','Não deu montagem','Peças não encaixam ou montagem inviável'],['estrutural','Faltou peça estrutural','Componente essencial ausente'],['mofo','Mofo em compra recente','Ocorrência próxima à entrega'],['mais50','Mais de 50% das peças quebradas','Dano predominante no produto'],['peca','Faltou ou quebrou uma peça','Componente isolado'],['outro','Outro relato','Situação não listada']],
  outro:[['peca','Faltou uma peça','Componente não enviado'],['quebrada','Uma peça quebrou/chegou quebrada','Dano isolado'],['mais50','Mais de 50% quebrado','Dano predominante'],['outro','Outro relato','Situação não listada']]
};
const state={step:1,supplier:'',product:'',issue:''};
const labels={colchao:'Colchão',estofado:'Estofado',madeira:'Móvel de madeira',outro:'Outro móvel'};
const input=document.querySelector('#supplierInput'), results=document.querySelector('#supplierResults');
const todayElement=document.querySelector('#today');
if(todayElement) todayElement.textContent=new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date()).replace('.','');

function normalize(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
function showSuppliers(value=''){
  const q=normalize(value.trim()); if(!q){results.innerHTML='';return}
  const matches=suppliers.filter(s=>normalize(s).includes(q)).slice(0,8);
  if(exclusiveTerms.some(x=>x.includes(q)) && !matches.some(s=>normalize(s).includes(q))) matches.unshift(value.toUpperCase());
  results.innerHTML=matches.length?matches.map(s=>`<button type="button" data-supplier="${s}">${s}${isExclusive(s)?'<small style="margin-left:auto;color:#0878f9">Atendimento direto</small>':''}</button>`).join(''):'<button type="button" disabled>Nenhum fornecedor ativo encontrado</button>';
}
function isExclusive(s){return exclusiveTerms.some(x=>normalize(s).includes(x))}
input.addEventListener('input',e=>showSuppliers(e.target.value));
results.addEventListener('click',e=>{const btn=e.target.closest('[data-supplier]');if(!btn)return;state.supplier=btn.dataset.supplier;input.value='';results.innerHTML='';const box=document.querySelector('#selectedSupplier');box.classList.remove('hidden');box.innerHTML=`<span>✓ <strong>${state.supplier}</strong> selecionado</span>${isExclusive(state.supplier)?'<b>Atendimento Magalu</b>':''}`;document.querySelector('[data-panel="1"] [data-next]').disabled=false});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();goTo(1);input.focus()}});

document.querySelectorAll('[data-product]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-product]').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');state.product=btn.dataset.product;document.querySelector('[data-panel="2"] [data-next]').disabled=false}));
function renderIssues(){document.querySelector('#issueChoices').innerHTML=issueMap[state.product].map(([id,title,desc])=>`<button type="button" class="choice" data-issue="${id}"><strong>${title}</strong><small>${desc}</small></button>`).join('')}
document.querySelector('#issueChoices').addEventListener('click',e=>{const btn=e.target.closest('[data-issue]');if(!btn)return;document.querySelectorAll('[data-issue]').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');state.issue=btn.dataset.issue;document.querySelector('[data-panel="3"] [data-next]').disabled=false});

function getDecision(){
  const exchange=['afundamento','barulho','mola','montagem','estrutural','mofo','mais50'].includes(state.issue);
  const parts=['peca','quebrada'].includes(state.issue);
  if(exchange)return{type:'exchange',icon:'↔',title:'Realizar troca do produto',tag:'TRATATIVA · TROCA',desc:'O cenário está coberto pela tratativa direta do pós-venda. Não direcione ao fabricante.',script:'Entendi o que aconteceu. Neste caso, nós mesmos vamos conduzir a solução por aqui, sem necessidade de você entrar em contato com o fabricante. Vou seguir com a tratativa de troca do produto.',action:'Troca do produto',macro:'Aplicar fluxo de troca conforme política vigente'};
  if(parts)return{type:'parts',icon:'✓',title:'Solicitar envio de peça',tag:'TRATATIVA · PEÇAS',desc:'Atenda diretamente com o envio da peça necessária. Não direcione ao fabricante.',script:'Entendi. Como o problema está em uma peça específica, vamos solicitar essa peça para resolver a situação sem que você precise procurar o fabricante.',action:'Pedido de peça',macro:'BKO > peças'};
  return{type:'review',icon:'?',title:'Analisar o caso antes de direcionar',tag:'TRATATIVA · ANÁLISE',desc:'O relato não está entre os cenários automáticos. Consulte a política vigente e não descarte por conter a palavra “quebrou”.',script:'Vou analisar os detalhes do seu caso para indicar a solução correta. Você não precisa acionar o fabricante neste momento; vou verificar a tratativa disponível por aqui.',action:'Análise conforme política vigente',macro:'Validar fluxo com apoio operacional'};
}
function renderResult(){const d=getDecision();const issue=issueMap[state.product].find(x=>x[0]===state.issue)?.[1];const exclusive=isExclusive(state.supplier);document.querySelector('#resultCard').className=`result-card ${d.type}`;document.querySelector('#resultCard').innerHTML=`<div class="result-icon">${d.icon}</div><div><h2>${d.title}</h2><p>${d.desc}</p></div><span class="tag">${d.tag}</span>`;document.querySelector('#customerScript').textContent=d.script;document.querySelector('#zendeskNote').value=`TRIAGEM DE MÓVEL\nFornecedor: ${state.supplier}\nProduto: ${labels[state.product]}\nRelato: ${issue}\nTratativa: ${d.action}\nMacro/fluxo: ${d.macro}\nAtendimento direto Magalu: ${exclusive?'Sim — marca exclusiva':'Sim — categoria móveis em garantia'}\nOrientação ao cliente: não acionar fabricante.`}
function goTo(n){if(n===3)renderIssues();if(n===4)renderResult();state.step=n;document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',+p.dataset.panel===n));document.querySelectorAll('.step').forEach(s=>{const x=+s.dataset.step;s.classList.toggle('active',x===n);s.classList.toggle('done',x<n)});document.querySelector('.workspace').scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>goTo(state.step+1)));document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>goTo(state.step-1)));
document.querySelectorAll('.step').forEach(b=>b.addEventListener('click',()=>{const n=+b.dataset.step;if(n<=state.step||n===2&&state.supplier||n===3&&state.product||n===4&&state.issue)goTo(n)}));
function toast(){const t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
async function copy(text){try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}toast()}
document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',()=>{const el=document.querySelector(`#${b.dataset.copy}`);copy(el.value||el.textContent)}));
document.querySelector('#copyAll').addEventListener('click',()=>copy(`${document.querySelector('#customerScript').textContent}\n\n${document.querySelector('#zendeskNote').value}`));
document.querySelector('#restart').addEventListener('click',()=>{state.step=1;state.supplier=state.product=state.issue='';document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));document.querySelectorAll('[data-next]').forEach(x=>x.disabled=true);document.querySelector('#selectedSupplier').classList.add('hidden');input.value='';goTo(1);input.focus()});
